### ISSUE TITLE
Non-album releases get tagged as Album

### ISSUE THREAD

**Issue by flemmingss** [derat/yambs#6]
I am importing this release with one track, it is then of course a Single.
On Qobuz ALL releses has /album/ in the URL, even when it is an EP,  a Single or whatever.
Example:
https://www.qobuz.com/no-en/album/wap-feat-megan-thee-stallion-explicit-cardi-b/u244786uiq6eb
![image](https://user-images.githubusercontent.com/25674067/209983847-dbe03703-0836-4cc6-844a-4cf1f9b9fcfe.png)

- Solution 1: Don't autofill **Primary Type:**
- Solution 2: Guess based on definition. Look at https://dittomusic.com/en/blog/albums-vs-eps-vs-singles-a-guide-to-releasing-music/

**Comment by derat** [comment]
Thanks for filing the issue! Unfortunately, I don't think there's any way to reliably detect whether something is a single, EP, or album:

* Something with just one track can be an album, e.g. <https://www.qobuz.com/us-en/album/glass-alva-noto-ryuichi-sakamoto/rga6lsoocqatb>.
* Something with five tracks can be an EP (e.g. <https://www.qobuz.com/dk-en/album/sap-alice-in-chains/0884977869965>), album (e.g. <https://www.qobuz.com/us-en/album/animals-pink-floyd/tv5c8tyo8y66b>), or single (e.g. <https://musicbrainz.org/release/4d8ac19d-9d2b-4249-9dd2-d6af8666cd51>).

The official MB definitions are at <https://musicbrainz.org/doc/Release_Group/Type>, but I think it mostly comes down to being whatever the artist calls it. :-/

I chose "album" as the default since it seems like it's probably the most-common case, but I agree that there's a risk of steering people toward accidentally using it on singles or EPs. If I were to guess the type instead, maybe something like the following would be better:

* If the release title ends with "EP", it's an EP.
* If <= 4 tracks and one track title matches the release title, it's probably a single.
* Otherwise, treat it as an album.

Any thoughts about the above?

**Comment by flemmingss** [comment]
sound like acceptable criteria for me 
maybe don't fill "Album" if it is less then 7 tracks (number by "feel").

Also (not relevant for this issue), for Qobuz i like to fill "Disambiguation:" like this:
"Qobuz" or "Qobuz Hi-Res" depending on if it is Hi-Res or not.
